"""Central bibliography for the course. build.py generates references.html from this.

Each entry:
    id       - stable slug, used as the HTML anchor and linked from lesson pages
               (e.g. "../references.html#kingma-ba-2014")
    authors  - display string, e.g. "Kingma, D. P., & Ba, J."
    sort_name - first author's surname, used only for alphabetizing the page
    year     - int
    title    - paper title
    url      - link to the paper (arXiv preferred); None if no good link is known
    landmark - True to show a gold star on the references page
"""

REFERENCES = [
    {
        "id": "kingma-ba-2014",
        "authors": "Kingma, D. P., & Ba, J.",
        "sort_name": "Kingma",
        "year": 2014,
        "title": "Adam: A Method for Stochastic Optimization",
        "url": "https://arxiv.org/abs/1412.6980",
        "landmark": True,
    },
    {
        "id": "krizhevsky-2012",
        "authors": "Krizhevsky, A., Sutskever, I., & Hinton, G. E.",
        "sort_name": "Krizhevsky",
        "year": 2012,
        "title": "ImageNet Classification with Deep Convolutional Neural Networks",
        "url": "https://papers.nips.cc/paper_files/paper/2012/hash/c399862d3b9d6b76c8436e924a68c45b-Abstract.html",
        "landmark": True,
    },
    {
        "id": "deng-2009",
        "authors": "Deng, J., Dong, W., Socher, R., Li, L.-J., Li, K., & Fei-Fei, L.",
        "sort_name": "Deng",
        "year": 2009,
        "title": "ImageNet: A Large-Scale Hierarchical Image Database",
        "url": "https://ieeexplore.ieee.org/document/5206848",
        "landmark": True,
    },
    {
        "id": "simonyan-zisserman-2014",
        "authors": "Simonyan, K., & Zisserman, A.",
        "sort_name": "Simonyan",
        "year": 2014,
        "title": "Very Deep Convolutional Networks for Large-Scale Image Recognition",
        "url": "https://arxiv.org/abs/1409.1556",
        "landmark": True,
    },
    {
        "id": "szegedy-2015",
        "authors": "Szegedy, C., Liu, W., Jia, Y., Sermanet, P., Reed, S., Anguelov, D., Erhan, D., Vanhoucke, V., & Rabinovich, A.",
        "sort_name": "Szegedy",
        "year": 2015,
        "title": "Going Deeper with Convolutions",
        "url": "https://arxiv.org/abs/1409.4842",
        "landmark": True,
    },
    {
        "id": "he-2015-resnet",
        "authors": "He, K., Zhang, X., Ren, S., & Sun, J.",
        "sort_name": "He",
        "year": 2015,
        "title": "Deep Residual Learning for Image Recognition",
        "url": "https://arxiv.org/abs/1512.03385",
        "landmark": True,
    },
    {
        "id": "ronneberger-2015",
        "authors": "Ronneberger, O., Fischer, P., & Brox, T.",
        "sort_name": "Ronneberger",
        "year": 2015,
        "title": "U-Net: Convolutional Networks for Biomedical Image Segmentation",
        "url": "https://arxiv.org/abs/1505.04597",
        "landmark": True,
    },
    {
        "id": "ren-2015",
        "authors": "Ren, S., He, K., Girshick, R., & Sun, J.",
        "sort_name": "Ren",
        "year": 2015,
        "title": "Faster R-CNN: Towards Real-Time Object Detection with Region Proposal Networks",
        "url": "https://arxiv.org/abs/1506.01497",
        "landmark": True,
    },
    {
        "id": "redmon-2016",
        "authors": "Redmon, J., Divvala, S., Girshick, R., & Farhadi, A.",
        "sort_name": "Redmon",
        "year": 2016,
        "title": "You Only Look Once: Unified, Real-Time Object Detection",
        "url": "https://arxiv.org/abs/1506.02640",
        "landmark": True,
    },
    {
        "id": "he-2017-maskrcnn",
        "authors": "He, K., Gkioxari, G., Dollár, P., & Girshick, R.",
        "sort_name": "He",
        "year": 2017,
        "title": "Mask R-CNN",
        "url": "https://arxiv.org/abs/1703.06870",
        "landmark": True,
    },
    {
        "id": "srivastava-2014",
        "authors": "Srivastava, N., Hinton, G., Krizhevsky, A., Sutskever, I., & Salakhutdinov, R.",
        "sort_name": "Srivastava",
        "year": 2014,
        "title": "Dropout: A Simple Way to Prevent Neural Networks from Overfitting",
        "url": "https://jmlr.org/papers/v15/srivastava14a.html",
        "landmark": True,
    },
    {
        "id": "lowe-2004",
        "authors": "Lowe, D. G.",
        "sort_name": "Lowe",
        "year": 2004,
        "title": "Distinctive Image Features from Scale-Invariant Keypoints",
        "url": "https://www.cs.ubc.ca/~lowe/papers/ijcv04.pdf",
        "landmark": True,
    },
    {
        "id": "dosovitskiy-2020",
        "authors": "Dosovitskiy, A., Beyer, L., Kolesnikov, A., Weissenborn, D., Zhai, X., Unterthiner, T., Dehghani, M., Minderer, M., Heigold, G., Gelly, S., Uszkoreit, J., & Houlsby, N.",
        "sort_name": "Dosovitskiy",
        "year": 2020,
        "title": "An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale",
        "url": "https://arxiv.org/abs/2010.11929",
        "landmark": True,
    },
    {
        "id": "radford-2021",
        "authors": "Radford, A., Kim, J. W., Hallacy, C., Ramesh, A., Goh, G., Agarwal, S., Sastry, G., Askell, A., Mishkin, P., Clark, J., Krueger, G., & Sutskever, I.",
        "sort_name": "Radford",
        "year": 2021,
        "title": "Learning Transferable Visual Models From Natural Language Supervision",
        "url": "https://arxiv.org/abs/2103.00020",
        "landmark": True,
    },
    {
        "id": "lecun-1998",
        "authors": "LeCun, Y., Bottou, L., Bengio, Y., & Haffner, P.",
        "sort_name": "LeCun",
        "year": 1998,
        "title": "Gradient-Based Learning Applied to Document Recognition",
        "url": "http://yann.lecun.com/exdb/publis/pdf/lecun-98.pdf",
        "landmark": True,
    },
    {
        "id": "fischler-bolles-1981",
        "authors": "Fischler, M. A., & Bolles, R. C.",
        "sort_name": "Fischler",
        "year": 1981,
        "title": "Random Sample Consensus: A Paradigm for Model Fitting with Applications to Image Analysis and Automated Cartography",
        "url": "https://dl.acm.org/doi/10.1145/358669.358692",
        "landmark": True,
    },
    {
        "id": "canny-1986",
        "authors": "Canny, J.",
        "sort_name": "Canny",
        "year": 1986,
        "title": "A Computational Approach to Edge Detection",
        "url": "https://ieeexplore.ieee.org/document/4767851",
        "landmark": True,
    },
    {
        "id": "otsu-1979",
        "authors": "Otsu, N.",
        "sort_name": "Otsu",
        "year": 1979,
        "title": "A Threshold Selection Method from Gray-Level Histograms",
        "url": "https://ieeexplore.ieee.org/document/4310076",
        "landmark": True,
    },
    {
        "id": "hough-1962",
        "authors": "Hough, P. V. C.",
        "sort_name": "Hough",
        "year": 1962,
        "title": "Method and Means for Recognizing Complex Patterns",
        "url": "https://patents.google.com/patent/US3069654A",
        "landmark": False,
    },
    {
        "id": "duda-hart-1972",
        "authors": "Duda, R. O., & Hart, P. E.",
        "sort_name": "Duda",
        "year": 1972,
        "title": "Use of the Hough Transformation to Detect Lines and Curves in Pictures",
        "url": "https://dl.acm.org/doi/10.1145/361237.361242",
        "landmark": False,
    },
    {
        "id": "marr-hildreth-1980",
        "authors": "Marr, D., & Hildreth, E.",
        "sort_name": "Marr",
        "year": 1980,
        "title": "Theory of Edge Detection",
        "url": "https://royalsocietypublishing.org/doi/10.1098/rspb.1980.0020",
        "landmark": False,
    },
    {
        "id": "daubechies-1988",
        "authors": "Daubechies, I.",
        "sort_name": "Daubechies",
        "year": 1988,
        "title": "Orthonormal Bases of Compactly Supported Wavelets",
        "url": "https://onlinelibrary.wiley.com/doi/10.1002/cpa.3160410705",
        "landmark": False,
    },
    {
        "id": "marcelja-1980",
        "authors": "Marcelja, S.",
        "sort_name": "Marcelja",
        "year": 1980,
        "title": "Mathematical Description of the Responses of Simple Cortical Cells",
        "url": "https://opg.optica.org/josa/abstract.cfm?uri=josa-70-11-1297",
        "landmark": False,
    },
    {
        "id": "daugman-1985",
        "authors": "Daugman, J. G.",
        "sort_name": "Daugman",
        "year": 1985,
        "title": "Uncertainty Relation for Resolution in Space, Spatial Frequency, and Orientation Optimized by Two-Dimensional Visual Cortical Filters",
        "url": "https://opg.optica.org/josaa/abstract.cfm?uri=josaa-2-7-1160",
        "landmark": False,
    },
    {
        "id": "harris-stephens-1988",
        "authors": "Harris, C., & Stephens, M.",
        "sort_name": "Harris",
        "year": 1988,
        "title": "A Combined Corner and Edge Detector",
        "url": "http://www.bmva.org/bmvc/1988/avc-88-023.pdf",
        "landmark": False,
    },
    {
        "id": "shi-tomasi-1994",
        "authors": "Shi, J., & Tomasi, C.",
        "sort_name": "Shi",
        "year": 1994,
        "title": "Good Features to Track",
        "url": "https://ieeexplore.ieee.org/document/323794",
        "landmark": False,
    },
    {
        "id": "lucas-kanade-1981",
        "authors": "Lucas, B. D., & Kanade, T.",
        "sort_name": "Lucas",
        "year": 1981,
        "title": "An Iterative Image Registration Technique with an Application to Stereo Vision",
        "url": "https://www.ri.cmu.edu/pub_files/pub3/lucas_bruce_d_1981_1/lucas_bruce_d_1981_1.pdf",
        "landmark": False,
    },
    {
        "id": "bayer-1976",
        "authors": "Bayer, B. E.",
        "sort_name": "Bayer",
        "year": 1976,
        "title": "Color Imaging Array",
        "url": "https://patents.google.com/patent/US3971065A",
        "landmark": False,
    },
    {
        "id": "zhang-2000",
        "authors": "Zhang, Z.",
        "sort_name": "Zhang",
        "year": 2000,
        "title": "A Flexible New Technique for Camera Calibration",
        "url": "https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/tr98-71.pdf",
        "landmark": False,
    },
    {
        "id": "glorot-bengio-2010",
        "authors": "Glorot, X., & Bengio, Y.",
        "sort_name": "Glorot",
        "year": 2010,
        "title": "Understanding the Difficulty of Training Deep Feedforward Neural Networks",
        "url": "https://proceedings.mlr.press/v9/glorot10a.html",
        "landmark": False,
    },
    {
        "id": "he-2015-kaiming",
        "authors": "He, K., Zhang, X., Ren, S., & Sun, J.",
        "sort_name": "He",
        "year": 2015,
        "title": "Delving Deep into Rectifiers: Surpassing Human-Level Performance on ImageNet Classification",
        "url": "https://arxiv.org/abs/1502.01852",
        "landmark": False,
    },
    {
        "id": "ioffe-szegedy-2015",
        "authors": "Ioffe, S., & Szegedy, C.",
        "sort_name": "Ioffe",
        "year": 2015,
        "title": "Batch Normalization: Accelerating Deep Network Training by Reducing Internal Covariate Shift",
        "url": "https://arxiv.org/abs/1502.03167",
        "landmark": False,
    },
    {
        "id": "simonyan-2013-saliency",
        "authors": "Simonyan, K., Vedaldi, A., & Zisserman, A.",
        "sort_name": "Simonyan",
        "year": 2013,
        "title": "Deep Inside Convolutional Networks: Visualising Image Classification Models and Saliency Maps",
        "url": "https://arxiv.org/abs/1312.6034",
        "landmark": False,
    },
    {
        "id": "selvaraju-2017",
        "authors": "Selvaraju, R. R., Cogswell, M., Das, A., Vedantam, R., Parikh, D., & Batra, D.",
        "sort_name": "Selvaraju",
        "year": 2017,
        "title": "Grad-CAM: Visual Explanations from Deep Networks via Gradient-based Localization",
        "url": "https://arxiv.org/abs/1610.02391",
        "landmark": False,
    },
    {
        "id": "rowley-baluja-kanade-1996",
        "authors": "Rowley, H. A., Baluja, S., & Kanade, T.",
        "sort_name": "Rowley",
        "year": 1996,
        "title": "Neural Network-Based Face Detection",
        "url": "https://www.ri.cmu.edu/publications/neural-network-based-face-detection/",
        "landmark": False,
    },
    {
        "id": "viola-jones-2001",
        "authors": "Viola, P., & Jones, M.",
        "sort_name": "Viola",
        "year": 2001,
        "title": "Rapid Object Detection Using a Boosted Cascade of Simple Features",
        "url": "https://www.cs.cmu.edu/~efros/courses/LBMV07/Papers/viola-cvpr-01.pdf",
        "landmark": False,
    },
    {
        "id": "vaswani-2017",
        "authors": "Vaswani, A., Shazeer, N., Parmar, N., Uszkoreit, J., Jones, L., Gomez, A. N., Kaiser, L., & Polosukhin, I.",
        "sort_name": "Vaswani",
        "year": 2017,
        "title": "Attention Is All You Need",
        "url": "https://arxiv.org/abs/1706.03762",
        "landmark": False,
    },
    {
        "id": "chen-2020-simclr",
        "authors": "Chen, T., Kornblith, S., Norouzi, M., & Hinton, G.",
        "sort_name": "Chen",
        "year": 2020,
        "title": "A Simple Framework for Contrastive Learning of Visual Representations",
        "url": "https://arxiv.org/abs/2002.05709",
        "landmark": False,
    },
    {
        "id": "caron-2021-dino",
        "authors": "Caron, M., Touvron, H., Misra, I., Jégou, H., Mairal, J., Bojanowski, P., & Joulin, A.",
        "sort_name": "Caron",
        "year": 2021,
        "title": "Emerging Properties in Self-Supervised Vision Transformers",
        "url": "https://arxiv.org/abs/2104.14294",
        "landmark": False,
    },
    {
        "id": "oquab-2023-dinov2",
        "authors": "Oquab, M., Darcet, T., Moutakanni, T., et al.",
        "sort_name": "Oquab",
        "year": 2023,
        "title": "DINOv2: Learning Robust Visual Features without Supervision",
        "url": "https://arxiv.org/abs/2304.07193",
        "landmark": False,
    },
    {
        "id": "kirillov-2023-sam",
        "authors": "Kirillov, A., Mintun, E., Ravi, N., et al.",
        "sort_name": "Kirillov",
        "year": 2023,
        "title": "Segment Anything",
        "url": "https://arxiv.org/abs/2304.02643",
        "landmark": False,
    },
    {
        "id": "yang-2024-depthanything",
        "authors": "Yang, L., Kang, B., Huang, Z., Xu, X., Feng, J., & Zhao, H.",
        "sort_name": "Yang",
        "year": 2024,
        "title": "Depth Anything: Unleashing the Power of Large-Scale Unlabeled Data",
        "url": "https://arxiv.org/abs/2401.10891",
        "landmark": False,
    },
    {
        "id": "wen-2024-foundationstereo",
        "authors": "Wen, B., Trepte, M., Aribido, J., Kautz, J., Gallo, O., & Birchfield, S.",
        "sort_name": "Wen",
        "year": 2025,
        "title": "FoundationStereo: Zero-Shot Stereo Matching",
        "url": "https://arxiv.org/abs/2501.09898",
        "landmark": False,
    },
    {
        "id": "wang-2024-vggt",
        "authors": "Wang, J., Chen, M., Karaev, N., Vedaldi, A., Rupprecht, C., & Novotny, D.",
        "sort_name": "Wang",
        "year": 2025,
        "title": "VGGT: Visual Geometry Grounded Transformer",
        "url": "https://arxiv.org/abs/2503.11651",
        "landmark": False,
    },
    {
        "id": "zhou-2019-rotation6d",
        "authors": "Zhou, Y., Barnes, C., Lu, J., Yang, J., & Li, H.",
        "sort_name": "Zhou",
        "year": 2019,
        "title": "On the Continuity of Rotation Representations in Neural Networks",
        "url": "https://arxiv.org/abs/1812.07035",
        "landmark": False,
    },
    {
        "id": "sohl-dickstein-2015",
        "authors": "Sohl-Dickstein, J., Weiss, E., Maheswaranathan, N., & Ganguli, S.",
        "sort_name": "Sohl-Dickstein",
        "year": 2015,
        "title": "Deep Unsupervised Learning using Nonequilibrium Thermodynamics",
        "url": "https://arxiv.org/abs/1503.03585",
        "landmark": False,
    },
    {
        "id": "ho-2020-ddpm",
        "authors": "Ho, J., Jain, A., & Abbeel, P.",
        "sort_name": "Ho",
        "year": 2020,
        "title": "Denoising Diffusion Probabilistic Models",
        "url": "https://arxiv.org/abs/2006.11239",
        "landmark": False,
    },
    {
        "id": "mildenhall-2020-nerf",
        "authors": "Mildenhall, B., Srinivasan, P. P., Tancik, M., Barron, J. T., Ramamoorthi, R., & Ng, R.",
        "sort_name": "Mildenhall",
        "year": 2020,
        "title": "NeRF: Representing Scenes as Neural Radiance Fields for View Synthesis",
        "url": "https://arxiv.org/abs/2003.08934",
        "landmark": False,
    },
    {
        "id": "kerbl-2023-gaussiansplatting",
        "authors": "Kerbl, B., Kopanas, G., Leimkühler, T., & Drettakis, G.",
        "sort_name": "Kerbl",
        "year": 2023,
        "title": "3D Gaussian Splatting for Real-Time Radiance Field Rendering",
        "url": "https://arxiv.org/abs/2308.04079",
        "landmark": False,
    },
]
